CREATE TABLE IF NOT EXISTS characters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL DEFAULT 'character',
  description TEXT,
  attributes TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS questions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL UNIQUE,
  attribute_key TEXT NOT NULL,
  category TEXT,
  priority INTEGER DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT OR IGNORE INTO questions (text, attribute_key, category, priority) VALUES
('Is your answer fictional?', 'fictional', NULL, 100),
('Is it a human being?', 'human', NULL, 95),
('Is it a real living thing?', 'real_living', NULL, 90),
('Is it male?', 'male', 'character', 80),
('Is it female?', 'female', 'character', 79),
('Is it from a movie?', 'from_movie', 'character', 75),
('Is it from a video game?', 'from_game', 'character', 74),
('Is it from a book?', 'from_book', 'character', 73),
('Is it from TV?', 'from_tv', 'character', 72),
('Is it from a comic book?', 'from_comic', 'character', 71),
('Is it the main character?', 'main_character', 'character', 68),
('Is it a villain?', 'villain', 'character', 67),
('Does it involve magic or supernatural powers?', 'supernatural', NULL, 64),
('Is it from a science fiction setting?', 'sci_fi', NULL, 63),
('Is it from a fantasy setting?', 'fantasy', NULL, 62),
('Is it animated?', 'animated', 'character', 60),
('Is it an object?', 'object', NULL, 55),
('Is it a place?', 'place', NULL, 54),
('Is it an animal?', 'animal', NULL, 53),
('Is it food or drink?', 'food', NULL, 52);

INSERT OR IGNORE INTO characters (name, category, description, attributes) VALUES
('Spider-Man','character','Marvel superhero with web-slinging powers.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_comic":1,"main_character":1}'),
('Darth Vader','character','Sith lord from Star Wars.','{"fictional":1,"human":1,"male":1,"from_movie":1,"villain":1,"sci_fi":1}'),
('Luke Skywalker','character','Jedi hero from Star Wars.','{"fictional":1,"human":1,"male":1,"from_movie":1,"main_character":1,"sci_fi":1}'),
('Yoda','character','Small Jedi master from Star Wars.','{"fictional":1,"male":1,"from_movie":1,"sci_fi":1,"supernatural":1}'),
('Harry Potter','character','Wizard protagonist from the Harry Potter series.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_book":1,"main_character":1,"fantasy":1,"supernatural":1}'),
('Hermione Granger','character','Brilliant witch from Harry Potter.','{"fictional":1,"human":1,"female":1,"from_movie":1,"from_book":1,"main_character":1,"fantasy":1,"supernatural":1}'),
('Voldemort','character','Dark wizard villain from Harry Potter.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_book":1,"villain":1,"fantasy":1,"supernatural":1}'),
('Simba','character','Lion king from Disney animation.','{"fictional":1,"male":1,"from_movie":1,"main_character":1,"animated":1,"animal":1}'),
('Woody','character','Cowboy toy from Toy Story.','{"fictional":1,"male":1,"from_movie":1,"main_character":1,"animated":1,"object":1}'),
('Buzz Lightyear','character','Space ranger toy from Toy Story.','{"fictional":1,"male":1,"from_movie":1,"main_character":1,"animated":1,"object":1,"sci_fi":1}'),
('Elsa','character','Queen with ice powers from Frozen.','{"fictional":1,"human":1,"female":1,"from_movie":1,"main_character":1,"animated":1,"fantasy":1,"supernatural":1}'),
('Moana','character','Wayfinder heroine from Disney.','{"fictional":1,"human":1,"female":1,"from_movie":1,"main_character":1,"animated":1}'),
('Jack Sparrow','character','Pirate captain from Pirates of the Caribbean.','{"fictional":1,"human":1,"male":1,"from_movie":1,"main_character":1}'),
('Iron Man','character','Armored Marvel superhero Tony Stark.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_comic":1,"main_character":1,"sci_fi":1}'),
('Captain America','character','Marvel super soldier hero.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_comic":1,"main_character":1,"sci_fi":1}'),
('Thanos','character','Marvel cosmic villain.','{"fictional":1,"male":1,"from_movie":1,"from_comic":1,"villain":1,"sci_fi":1}'),
('The Joker','character','Batman villain and chaos enthusiast.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_comic":1,"villain":1}'),
('Batman','character','Gotham detective superhero.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_comic":1,"main_character":1}'),
('Wonder Woman','character','Amazon superhero from DC Comics.','{"fictional":1,"human":1,"female":1,"from_movie":1,"from_comic":1,"main_character":1,"fantasy":1}'),
('Forrest Gump','character','Kind-hearted film protagonist.','{"fictional":1,"human":1,"male":1,"from_movie":1,"main_character":1}'),
('The Dude','character','Laid-back protagonist of The Big Lebowski.','{"fictional":1,"human":1,"male":1,"from_movie":1,"main_character":1}'),
('Tyler Durden','character','Antagonistic figure from Fight Club.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_book":1,"villain":1}'),
('Princess Leia','character','Rebel leader from Star Wars.','{"fictional":1,"human":1,"female":1,"from_movie":1,"main_character":1,"sci_fi":1}'),
('Ellen Ripley','character','Alien franchise survivor.','{"fictional":1,"human":1,"female":1,"from_movie":1,"main_character":1,"sci_fi":1}'),
('Indiana Jones','character','Archaeologist adventurer.','{"fictional":1,"human":1,"male":1,"from_movie":1,"main_character":1}'),
('James Bond','character','British spy and film icon.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_book":1,"main_character":1}'),
('Katniss Everdeen','character','Archer protagonist from The Hunger Games.','{"fictional":1,"human":1,"female":1,"from_movie":1,"from_book":1,"main_character":1,"sci_fi":1}'),
('Frodo Baggins','character','Ring bearer from The Lord of the Rings.','{"fictional":1,"male":1,"from_movie":1,"from_book":1,"main_character":1,"fantasy":1}'),
('Gandalf','character','Wizard from Middle-earth.','{"fictional":1,"male":1,"from_movie":1,"from_book":1,"fantasy":1,"supernatural":1}'),
('Gollum','character','Ring-obsessed creature from Middle-earth.','{"fictional":1,"male":1,"from_movie":1,"from_book":1,"fantasy":1}'),
('Mario','character','Nintendo plumber hero.','{"fictional":1,"human":1,"male":1,"from_game":1,"main_character":1,"animated":1}'),
('Luigi','character','Mario brother and reluctant hero.','{"fictional":1,"human":1,"male":1,"from_game":1,"main_character":1,"animated":1}'),
('Princess Peach','character','Mushroom Kingdom princess.','{"fictional":1,"human":1,"female":1,"from_game":1,"main_character":1,"animated":1,"fantasy":1}'),
('Link','character','Hero from The Legend of Zelda.','{"fictional":1,"male":1,"from_game":1,"main_character":1,"fantasy":1}'),
('Zelda','character','Princess from The Legend of Zelda.','{"fictional":1,"female":1,"from_game":1,"main_character":1,"fantasy":1,"supernatural":1}'),
('Sonic','character','Fast blue hedgehog.','{"fictional":1,"male":1,"from_game":1,"main_character":1,"animated":1,"animal":1}'),
('Pikachu','character','Electric Pokemon mascot.','{"fictional":1,"from_game":1,"main_character":1,"animated":1,"animal":1,"supernatural":1}'),
('Kratos','character','God-slaying warrior from God of War.','{"fictional":1,"human":1,"male":1,"from_game":1,"main_character":1,"fantasy":1,"supernatural":1}'),
('Master Chief','character','Armored supersoldier from Halo.','{"fictional":1,"human":1,"male":1,"from_game":1,"main_character":1,"sci_fi":1}'),
('Lara Croft','character','Tomb-raiding video game adventurer.','{"fictional":1,"human":1,"female":1,"from_game":1,"main_character":1}'),
('Pac-Man','character','Arcade maze icon.','{"fictional":1,"male":1,"from_game":1,"main_character":1,"animated":1}'),
('Donkey Kong','character','Nintendo ape.','{"fictional":1,"male":1,"from_game":1,"main_character":1,"animated":1,"animal":1}'),
('Samus Aran','character','Bounty hunter from Metroid.','{"fictional":1,"human":1,"female":1,"from_game":1,"main_character":1,"sci_fi":1}'),
('Cloud Strife','character','Mercenary hero from Final Fantasy VII.','{"fictional":1,"human":1,"male":1,"from_game":1,"main_character":1,"fantasy":1,"sci_fi":1}'),
('Sephiroth','character','Final Fantasy VII antagonist.','{"fictional":1,"human":1,"male":1,"from_game":1,"villain":1,"fantasy":1,"sci_fi":1}'),
('Homer Simpson','character','Animated father from The Simpsons.','{"fictional":1,"human":1,"male":1,"from_tv":1,"main_character":1,"animated":1}'),
('Peter Griffin','character','Animated father from Family Guy.','{"fictional":1,"human":1,"male":1,"from_tv":1,"main_character":1,"animated":1}'),
('SpongeBob SquarePants','character','Animated sponge from Bikini Bottom.','{"fictional":1,"male":1,"from_tv":1,"main_character":1,"animated":1,"animal":1}'),
('Patrick Star','character','Animated starfish from SpongeBob.','{"fictional":1,"male":1,"from_tv":1,"animated":1,"animal":1}'),
('Jerry Mouse','character','Mouse from Tom and Jerry.','{"fictional":1,"male":1,"from_tv":1,"main_character":1,"animated":1,"animal":1}'),
('Bugs Bunny','character','Looney Tunes rabbit.','{"fictional":1,"male":1,"from_tv":1,"main_character":1,"animated":1,"animal":1}'),
('Scooby-Doo','character','Mystery-solving dog.','{"fictional":1,"male":1,"from_tv":1,"main_character":1,"animated":1,"animal":1}'),
('Sherlock Holmes','character','Detective from classic fiction.','{"fictional":1,"human":1,"male":1,"from_book":1,"main_character":1}'),
('Wednesday Addams','character','Macabre Addams Family member.','{"fictional":1,"human":1,"female":1,"from_tv":1,"from_movie":1,"main_character":1}'),
('Jean-Luc Picard','character','Starfleet captain from Star Trek.','{"fictional":1,"human":1,"male":1,"from_tv":1,"main_character":1,"sci_fi":1}'),
('Walter White','character','Chemistry teacher turned criminal.','{"fictional":1,"human":1,"male":1,"from_tv":1,"main_character":1,"villain":1}'),
('Daenerys Targaryen','character','Dragon-riding queen from Game of Thrones.','{"fictional":1,"human":1,"female":1,"from_tv":1,"from_book":1,"main_character":1,"fantasy":1}'),
('Jon Snow','character','Hero from Game of Thrones.','{"fictional":1,"human":1,"male":1,"from_tv":1,"from_book":1,"main_character":1,"fantasy":1}'),
('Eleven','character','Telekinetic character from Stranger Things.','{"fictional":1,"human":1,"female":1,"from_tv":1,"main_character":1,"sci_fi":1,"supernatural":1}'),
('Mickey Mouse','character','Disney mouse mascot.','{"fictional":1,"male":1,"from_movie":1,"from_tv":1,"main_character":1,"animated":1,"animal":1}'),
('Albert Einstein','character','Real theoretical physicist.','{"human":1,"real_living":1,"male":1}'),
('Michael Jordan','character','Real basketball legend.','{"human":1,"real_living":1,"male":1}'),
('Elvis Presley','character','Real singer and cultural icon.','{"human":1,"real_living":1,"male":1}'),
('Taylor Swift','character','Real singer-songwriter.','{"human":1,"real_living":1,"female":1}'),
('LeBron James','character','Real basketball player.','{"human":1,"real_living":1,"male":1}'),
('Beyonce','character','Real singer and performer.','{"human":1,"real_living":1,"female":1}'),
('Isaac Newton','character','Real physicist and mathematician.','{"human":1,"real_living":1,"male":1}'),
('William Shakespeare','character','Real playwright and poet.','{"human":1,"real_living":1,"male":1}'),
('Abraham Lincoln','character','Real U.S. president.','{"human":1,"real_living":1,"male":1}'),
('Cleopatra','character','Real queen of ancient Egypt.','{"human":1,"real_living":1,"female":1}'),
('Mona Lisa','object','Famous portrait painting.','{"object":1}'),
('Golden Snitch','object','Flying ball from Quidditch.','{"fictional":1,"object":1,"from_movie":1,"from_book":1,"fantasy":1,"supernatural":1}'),
('One Ring','object','Powerful ring from The Lord of the Rings.','{"fictional":1,"object":1,"from_movie":1,"from_book":1,"fantasy":1,"supernatural":1}'),
('Lightsaber','object','Energy sword from Star Wars.','{"fictional":1,"object":1,"from_movie":1,"sci_fi":1}'),
('Death Star','object','Planet-destroying space station.','{"fictional":1,"object":1,"from_movie":1,"sci_fi":1}'),
('TARDIS','object','Time-traveling police box from Doctor Who.','{"fictional":1,"object":1,"from_tv":1,"sci_fi":1}'),
('Mjolnir','object','Thor hammer from Norse myth and Marvel.','{"fictional":1,"object":1,"from_movie":1,"from_comic":1,"fantasy":1,"supernatural":1}'),
('Infinity Gauntlet','object','Marvel artifact for Infinity Stones.','{"fictional":1,"object":1,"from_movie":1,"from_comic":1,"sci_fi":1,"supernatural":1}'),
('Sorting Hat','object','Talking hat from Harry Potter.','{"fictional":1,"object":1,"from_movie":1,"from_book":1,"fantasy":1,"supernatural":1}'),
('Flux Capacitor','object','Time travel device from Back to the Future.','{"fictional":1,"object":1,"from_movie":1,"sci_fi":1}'),
('Niffler','character','Treasure-loving magical creature.','{"fictional":1,"from_movie":1,"from_book":1,"animal":1,"fantasy":1,"supernatural":1}'),
('Grass','object','Common real plant ground cover.','{"real_living":1}'),
('Pizza','object','Popular food.','{"object":1,"food":1}'),
('Coffee','object','Caffeinated drink.','{"object":1,"food":1}'),
('Hogwarts','place','Wizarding school from Harry Potter.','{"fictional":1,"place":1,"from_movie":1,"from_book":1,"fantasy":1,"supernatural":1}'),
('Narnia','place','Fantasy world reached through a wardrobe.','{"fictional":1,"place":1,"from_movie":1,"from_book":1,"fantasy":1,"supernatural":1}'),
('Mordor','place','Dark realm in Middle-earth.','{"fictional":1,"place":1,"from_movie":1,"from_book":1,"fantasy":1}'),
('Wakanda','place','Fictional African nation from Marvel.','{"fictional":1,"place":1,"from_movie":1,"from_comic":1,"sci_fi":1}'),
('Atlantis','place','Legendary underwater city.','{"fictional":1,"place":1,"fantasy":1}'),
('Gotham City','place','Batman home city.','{"fictional":1,"place":1,"from_movie":1,"from_comic":1}'),
('Metropolis','place','Superman home city.','{"fictional":1,"place":1,"from_movie":1,"from_comic":1}'),
('Middle-earth','place','Fantasy setting of Tolkien stories.','{"fictional":1,"place":1,"from_movie":1,"from_book":1,"fantasy":1}'),
('Bikini Bottom','place','Undersea town from SpongeBob.','{"fictional":1,"place":1,"from_tv":1,"animated":1}'),
('Springfield','place','Home city of The Simpsons.','{"fictional":1,"place":1,"from_tv":1,"animated":1}'),
('Jurassic Park','place','Dinosaur theme park setting.','{"fictional":1,"place":1,"from_movie":1,"from_book":1,"sci_fi":1}'),
('Emerald City','place','Capital city in Oz.','{"fictional":1,"place":1,"from_movie":1,"from_book":1,"fantasy":1}'),
('Death Valley','place','Real desert valley in the United States.','{"place":1}'),
('Mount Everest','place','Real highest mountain on Earth.','{"place":1}'),
('Superman','character','DC superhero from Krypton.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_comic":1,"main_character":1,"sci_fi":1}'),
('Dumbledore','character','Headmaster wizard from Harry Potter.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_book":1,"fantasy":1,"supernatural":1}'),
('Black Panther','character','Marvel hero and king of Wakanda.','{"fictional":1,"human":1,"male":1,"from_movie":1,"from_comic":1,"main_character":1,"sci_fi":1}'),
('Dora the Explorer','character','Animated child explorer from TV.','{"fictional":1,"human":1,"female":1,"from_tv":1,"main_character":1,"animated":1}'),
('Coca-Cola','object','Popular soft drink.','{"object":1,"food":1}');
